### ISSUE TITLE
Missing nwjs enviroment

### ISSUE THREAD

**Issue by teawithfruit** [konsumer/react-nodewebkit#1]
If i implement something like this `var gui = require('nw.gui');` in `app/jsx/index.jsx` watchify is rising the following error:

```
Error: Cannot find module 'nw.gui' from '/Development/App/app/jsx'
```

I think that the error came up, because of the missing nwjs enviroment. Do you have an idea to fix that?

**Comment by konsumer** [comment]
`nw.gui` is only available in nodewebkit environment. The system should abstract away the lib, so it works in a browser. Can I see your code? I bet there is some added code that is requiring the native stuff, somewhere.

**Comment by teawithfruit** [comment]
Yes, of course. The only additional line is the line i've posted already. My index.jsx looks like this.

```
/* @jsx React.DOM */

var React = require('react');
var HelloWorld = require('./components/HelloWorld.jsx');

var gui = require('nw.gui');

React.render(<HelloWorld />, document.getElementById('content'));
```

**Comment by konsumer** [comment]
Yeah, so you can use it without that line, or shim it as I have done with the native serial, in the README. The idea of the shim is to make a fake interface for native thing while developing in a non-native environment, like a browser.

**Comment by Leksat** [comment]
@teawithfruit, you are using

```
var gui = require('nw.gui');
```

while you need

```
var gui = nativeRequire('nw.gui');
```
